// Shared UI render helpers (return HTML strings) + Chart.js wrappers.
import { icon } from './icons.js';

export const COLORS = {
  positive: '#0e700e', neutral: '#616161', negative: '#c4314b', warning: '#bc4b09', info: '#0f6cbd',
  sev1: '#a80000', sev2: '#c4314b', sev3: '#bc4b09', sev4: '#616161', brand: '#0f6cbd',
};
export const CHART_PALETTE = ['#0f6cbd', '#2aa0a4', '#6b69d6', '#f7a600', '#c4314b', '#5c2e91', '#0e700e'];

export function esc(v) {
  return String(v == null ? '' : v).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}
export const scoreColor = (s) => (s >= 4.4 ? COLORS.positive : s >= 3.8 ? COLORS.warning : COLORS.negative);
export const utilColor = (p) => (p >= 80 && p <= 92 ? COLORS.positive : p > 92 ? COLORS.negative : p >= 65 ? COLORS.warning : COLORS.neutral);

export function aiChip(label = 'AI-generated') {
  return `<span class="ai-chip" role="note" title="Simulated AI output. Advisory only — a human decides. In production, generated by Azure OpenAI over SSD IQ.">${icon('sparkle', 14)}${esc(label)}</span>`;
}

const STATUS = {
  new: [COLORS.info, 'clock', 'New'], assigned: [COLORS.info, 'clock', 'Assigned'],
  'in-delivery': [COLORS.warning, 'clock', 'In delivery'], complete: [COLORS.positive, 'check', 'Complete'],
  investigating: [COLORS.warning, 'clock', 'Investigating'], mitigating: [COLORS.info, 'clock', 'Mitigating'],
  resolved: [COLORS.positive, 'check', 'Resolved'], open: [COLORS.negative, 'warning', 'Open'],
  'in-progress': [COLORS.warning, 'clock', 'In progress'], done: [COLORS.positive, 'check', 'Done'],
  sourcing: [COLORS.neutral, 'clock', 'Sourcing'], selection: [COLORS.neutral, 'clock', 'Selection'],
  onboarding: [COLORS.info, 'clock', 'Onboarding'], active: [COLORS.positive, 'check', 'Active'],
  offboarding: [COLORS.warning, 'clock', 'Offboarding'], exiting: [COLORS.warning, 'clock', 'Exiting'],
  draft: [COLORS.neutral, 'clock', 'Draft'], closed: [COLORS.neutral, 'check', 'Closed'],
};
export function statusPill(status) {
  const [c, ic, label] = STATUS[status] || [COLORS.neutral, 'clock', status];
  return `<span class="pill" style="color:${c}">${icon(ic, 14)}<span class="pill-label">${esc(label)}</span></span>`;
}
const SEV = { sev1: [COLORS.sev1, 'Sev 1'], sev2: [COLORS.sev2, 'Sev 2'], sev3: [COLORS.sev3, 'Sev 3'], sev4: [COLORS.sev4, 'Sev 4'] };
export function severityPill(sev) {
  const [c, label] = SEV[sev] || [COLORS.neutral, sev];
  return `<span class="pill" style="color:${c}">${icon('warning', 14)}<span class="pill-label">${esc(label)}</span></span>`;
}
const SENT = { positive: [COLORS.positive, 'thumbUp', 'Positive'], neutral: [COLORS.neutral, 'minus', 'Neutral'], negative: [COLORS.negative, 'thumbDown', 'Negative'] };
export function sentimentPill(s) {
  const [c, ic, label] = SENT[s] || [COLORS.neutral, 'minus', s];
  return `<span class="pill" style="color:${c}">${icon(ic, 14)}<span class="pill-label">${esc(label)}</span></span>`;
}
export function sourceBadge(source) {
  return `<span class="source-badge" title="Source of truth: ${esc(source)}">${icon('database', 12)}${esc(source)}</span>`;
}
export function badge(text, variant = 'outline') {
  return `<span class="badge ${variant}">${esc(text)}</span>`;
}
export function kpiCard({ label, value, hint, tone, iconName }) {
  return `<div class="card kpi">
    <div class="kpi-head">
      ${iconName ? `<span class="kpi-ico">${icon(iconName, 18)}</span>` : ''}
      <span class="kpi-label">${esc(label)}</span>
    </div>
    <div class="kpi-value" style="${tone ? `color:${tone}` : ''}">${esc(value)}</div>
    ${hint ? `<div class="kpi-hint">${esc(hint)}</div>` : ''}
  </div>`;
}
export function pageHeader({ title, description, actions }) {
  return `<div class="page-head">
    <div>
      <h1 class="page-title">${esc(title)}</h1>
      ${description ? `<div class="page-desc">${esc(description)}</div>` : ''}
    </div>
    ${actions ? `<div class="page-actions">${actions}</div>` : ''}
  </div>`;
}
export function emptyState({ title, description }) {
  return `<div class="empty">${icon('docSearch', 32)}<div style="font-weight:600">${esc(title)}</div>${description ? `<div class="muted">${esc(description)}</div>` : ''}</div>`;
}

// ---- Charts (global Chart from vendored UMD) ----
let activeCharts = [];
export function clearCharts() { activeCharts.forEach((c) => { try { c.destroy(); } catch (e) { /* noop */ } }); activeCharts = []; }
function chartTheme() {
  const dark = document.documentElement.getAttribute('data-theme') === 'dark';
  return { text: dark ? '#c8c6c4' : '#605e5c', grid: dark ? '#3a3a40' : '#ededed', border: dark ? '#1f2023' : '#ffffff' };
}
function mk(canvas, cfg) { window.Chart.defaults.color = chartTheme().text; window.Chart.defaults.font.family = 'Segoe UI'; const ch = new window.Chart(canvas, cfg); activeCharts.push(ch); return ch; }

export function donut(canvas, { labels, values, colors }) {
  return mk(canvas, {
    type: 'doughnut',
    data: { labels, datasets: [{ data: values, backgroundColor: colors || CHART_PALETTE, borderWidth: 2, borderColor: chartTheme().border }] },
    options: { responsive: true, maintainAspectRatio: false, cutout: '62%', plugins: { legend: { position: 'bottom', labels: { boxWidth: 10, usePointStyle: true, font: { family: 'Segoe UI' } } } } },
  });
}
export function bar(canvas, { labels, values, color, label }) {
  return mk(canvas, {
    type: 'bar',
    data: { labels, datasets: [{ label: label || '', data: values, backgroundColor: color || COLORS.brand, borderRadius: 4, maxBarThickness: 46 }] },
    options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } }, scales: { x: { grid: { display: false } }, y: { beginAtZero: true, grid: { color: chartTheme().grid } } } },
  });
}
export function line(canvas, { labels, datasets }) {
  return mk(canvas, {
    type: 'line',
    data: { labels, datasets: datasets.map((d, i) => ({ label: d.label, data: d.values, borderColor: d.color || CHART_PALETTE[i % CHART_PALETTE.length], backgroundColor: 'transparent', tension: 0.3, borderWidth: 2, pointRadius: 2 })) },
    options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { position: 'bottom', labels: { usePointStyle: true, boxWidth: 10 } } }, scales: { x: { grid: { display: false } }, y: { grid: { color: chartTheme().grid } } } },
  });
}

// ---- Kanban ----
export function kanban(columns) {
  return `<div class="kanban">${columns.map((c) => `
    <div class="kan-col">
      <div class="kan-head"><span>${esc(c.title)}</span><span class="kan-count">${c.count}</span></div>
      <div class="kan-cards">${c.cards.join('') || '<div class="muted" style="padding:8px;font-size:12px">None</div>'}</div>
    </div>`).join('')}</div>`;
}

// ---- Meter (progress bar) ----
export function meter(pct, color) {
  return `<div class="meter"><div class="meter-fill" style="width:${Math.max(0, Math.min(100, pct))}%;background:${color || COLORS.brand}"></div></div>`;
}

// ---- Shared body-level drawer ----
export function openDrawer(title, bodyHtml, wire) {
  let scrim = document.getElementById('g-scrim');
  let dr = document.getElementById('g-drawer');
  if (!scrim) { scrim = document.createElement('div'); scrim.id = 'g-scrim'; scrim.className = 'drawer-scrim'; document.body.appendChild(scrim); scrim.addEventListener('click', closeDrawer); }
  if (!dr) { dr = document.createElement('aside'); dr.id = 'g-drawer'; dr.className = 'drawer'; document.body.appendChild(dr); }
  dr.innerHTML = `<div class="drawer-head"><span class="drawer-title">${title}</span><button class="icon-btn" id="g-drawer-close" aria-label="Close" style="color:var(--fg-2)">${icon('x', 20)}</button></div><div class="drawer-body">${bodyHtml}</div>`;
  scrim.classList.add('open'); dr.classList.add('open');
  dr.querySelector('#g-drawer-close').addEventListener('click', closeDrawer);
  if (wire) wire(dr);
}
export function closeDrawer() {
  const s = document.getElementById('g-scrim'); const d = document.getElementById('g-drawer');
  if (s) s.classList.remove('open'); if (d) d.classList.remove('open');
}
